### ISSUE TITLE
Support for Modern WebView ?

### ISSUE THREAD

**Issue by kalliwoda** [NeutroniumCore/Neutronium#75] opened 2018-03-22 17:28 UTC
Microsoft have announced that there will be a 'Modern WebView' which wraps the Edge browser and will run as a component (in a separate process) within a WPF app ...

https://blogs.windows.com/buildingapps/2018/03/07/three-things-need-know-windows-developer-day/

Are there plans to support this within Neutronuim as an alternative WebBrowserEngine option ? At the moment there doesn't seem to be any real information about it, but using a 'native' browser engine (which will inherently keep in sync with security updates etc?) seems like quite an attractive idea.

**Comment by David-Desmaisons** [comment] 2018-03-25 15:02
Hello @kalliwoda , well I keep an eye on the upcoming C#  browser implementation. As you mentioned there seems that there is not very much documentation about "Modern WebView" for now.
A real motivator to create a new binding to a WebBrowser would be to have a cross platform implementation (meaning having to use something like avalonia instead of WPF).
So for now, I have no plan to migrate to Modern WebView.

**Comment by kalliwoda** [comment] 2018-03-25 18:10
That's a v interesting prospect - to use Avalonia for the basic 'shell' of an application, and browser windows for rendering complex graphics (eg using SVG/D3), all cross-platform. I would imagine that your MVVM helper classes would migrate over to that pretty nicely ?

**Comment by David-Desmaisons** [comment] 2018-03-26 00:05
Well, this is discussed in details in issue  #58 .
Great part of Neutronium ignore WPF, so implementating other framework would be straightforward.

**Comment by mattkol** [comment] 2018-03-30 09:30
Disclaimer: I am the creator of [Chromely](https://github.com/mattkol/Chromely).

Using basic "shell" is the primary focus of  [Chromely](https://github.com/mattkol/Chromely). It uses native GUI APIs to host CefGlue and CefSharp. With CefGlue, it is cross-platform and supports both .NET and .NET Core.

**Comment by David-Desmaisons** [comment] 2018-11-19 02:30
Duplicate of #58.

**Closed by David-Desmaisons** 2018-11-19 02:30 UTC
Labels: enhancement
