### ISSUE TITLE
Chromium.CfxRemotingException

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#43] opened 2017-11-22 22:23 UTC
Got some Neutronium-related exceptions collected from the users.

These exceptions have 1-2 occurences across 300+ beta users.

```
Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Failed to read past end of stream.
   в System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   в System.IO.BinaryReader.ReadUInt16()
   в Chromium.Remote.RemoteConnection.ReadLoop()
   в Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- Конец трассировки внутреннего стека исключений ---
   в Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   в Chromium.Remote.CfrTaskRunner.PostTask(CfrTask task)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.RunInContext(Action action)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxWebView.Dispatch(Action act)
   в Neutronium.Core.Binding.BidirectionalMapper.DispatchInJavascriptContext(Action run)
   в Neutronium.Core.Binding.BidirectionalMapper.UpdateFromCSharpChanges(Object newCSharpObject, Func`2 updaterBuilder)
   в Neutronium.Core.Binding.BidirectionalMapper.OnCSharpPropertyChanged(Object sender, PropertyChangedEventArgs e)
   в System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   в Miner.BindableBase.OnPropertyChanged(String propertyName)
   в Miner.BindableBase.SetProperty[T](T& storage, T value, String propertyName)
   в Miner.MainViewModel.set_Visible(Boolean value)
   в Miner.MainViewModel.Hide()
   в Miner.MainWindow.OnClosing(CancelEventArgs e)
   в System.Windows.Window.WmClose()
   в System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.UnsafeSendMessage(IntPtr hWnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)
   в System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   в System.Windows.Application.DoShutdown()
   в System.Windows.Application.ShutdownImpl()
   в System.Windows.Application.ShutdownCallback(Object arg)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.Run()
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в System.Windows.Application.Run()
   в Miner.Program.Main()
```

```
Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Failed to read past end of stream.
   в System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   в System.IO.BinaryReader.ReadUInt16()
   в Chromium.Remote.RemoteConnection.ReadLoop()
   в Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- Конец трассировки внутреннего стека исключений ---
   в Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   в Chromium.Remote.CfrTaskRunner.PostTask(CfrTask task)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.RunInContext(Action action)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxWebView.Dispatch(Action act)
   в Neutronium.Core.Binding.BidirectionalMapper.DispatchInJavascriptContext(Action run)
   в Neutronium.Core.Binding.BidirectionalMapper.UpdateFromCSharpChanges(Object newCSharpObject, Func`2 updaterBuilder)
   в Neutronium.Core.Binding.BidirectionalMapper.OnCSharpPropertyChanged(Object sender, PropertyChangedEventArgs e)
   в System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   в Miner.BindableBase.OnPropertyChanged(String propertyName)
   в Miner.BindableBase.SetProperty[T](T& storage, T value, String propertyName)
   в Miner.MainViewModel.set_Visible(Boolean value)
   в Miner.MainViewModel.Hide()
   в Miner.MainWindow.OnClosing(CancelEventArgs e)
   в System.Windows.Window.WmClose()
   в System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.UnsafeSendMessage(IntPtr hWnd, WindowMessage msg, IntPtr wParam, IntPtr lParam)
   в System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   в System.Windows.Application.DoShutdown()
   в System.Windows.Application.ShutdownImpl()
   в System.Windows.Application.ShutdownCallback(Object arg)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в System.Windows.Application.Run()
   в Miner.Program.Main()
```

```
Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.IOException: Pipe is broken.
   в System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   в System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   в System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   в Chromium.Remote.PipeBufferStream.Flush()
   в System.IO.BinaryWriter.Flush()
   в Chromium.Remote.RemoteCall.WriteRequest(StreamHandler h)
   в Chromium.Remote.RemoteConnection.Write(Action`1 callback)
   --- Конец трассировки внутреннего стека исключений ---
   в Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   в Chromium.Remote.CfrTaskRunner.PostTask(CfrTask task)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.RunInContext(Action action)
   в Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxWebView.Dispatch(Action act)
   в Neutronium.Core.Binding.BidirectionalMapper.DispatchInJavascriptContext(Action run)
   в Neutronium.Core.Binding.BidirectionalMapper.UpdateFromCSharpChanges(Object newCSharpObject, Func`2 updaterBuilder)
   в Neutronium.Core.Binding.BidirectionalMapper.OnCSharpPropertyChanged(Object sender, PropertyChangedEventArgs e)
   в System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   в Miner.BindableBase.OnPropertyChanged(String propertyName)
   в Miner.MainViewModel.<>c__DisplayClass195_0.<Model_PropertyChanged>b__0()
   в System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   в System.Windows.Threading.Dispatcher.Invoke(Action callback)
   в Miner.MainViewModel.Model_PropertyChanged(Object sender, PropertyChangedEventArgs e)
   в Miner.BindableBase.OnPropertyChanged(String propertyName)
   в Miner.MainModel.OnHashrateChanged(Dictionary`2 hashrate)
   в System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   в System.Reactive.Linq.ObservableImpl.Where`1._.OnNext(TSource value)
   в System.Reactive.Concurrency.ObserveOn`1.ObserveOnSink.OnNextPosted(Object value)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.DispatcherOperation.InvokeImpl()
   в System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Threading.DispatcherOperation.Invoke()
   в System.Windows.Threading.Dispatcher.ProcessQueue()
   в System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   в System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   в System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   в System.Windows.Application.RunDispatcher(Object ignore)
   в System.Windows.Application.RunInternal(Window window)
   в System.Windows.Application.Run(Window window)
   в System.Windows.Application.Run()
   в Miner.Program.Main()
```

**Comment by o2genum** [comment] 2017-11-22 22:41
P.S.: Could you make a new release? I just need that critical #37 fix, but it's inconvenient to use my own Neutronium build with CI, for example.

**Comment by David-Desmaisons** [comment] 2017-11-22 23:21
1) I will release new nugets this week-end.
2) From the 2 first stacks, I can see that some updates are done during the closing: Neutronium is called to refresh a binding at a time that the browser has already been closed. 
Check if you call Dispose on the HTMLViewControl control on the OnClosing events

**Comment by o2genum** [comment] 2017-11-23 01:01
Ok, so this is the same thing, something gets updated when the browser's been already disposed. I think all the exceptions are related, thanks.

**Comment by David-Desmaisons** [comment] 2017-11-24 02:15
Hello @o2genum , I just released version 1.0.1 containing correction for issue #37

**Comment by o2genum** [comment] 2017-11-28 01:49
After a `HtmlViewControl.Dispose()` call I can update ViewModel without a problem. The control is blank, of course, but it causes no exception.

But I've found how to get a `Chromium.CfxRemotingException`:

1. Start a Neutronium app that has a timer that updates ViewModel every second.
2. Kill ChromiumFXRenderProcess repeatedly (PowerShell):
```PowerShell
While(1) {
Stop-Process -processname ChromiumFXRenderProcess
}
```
3. `ChromiumFXRenderProcess` restarts a few times.
3. In a few seconds I get a random `Chromium.CfxRemotingException`.

I catch it like this to prevent the app from crashing:
```cs
    public class BindableBase : INotifyPropertyChanged
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public event PropertyChangedEventHandler PropertyChanged;

        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;

            storage = value;
            this.OnPropertyChanged(propertyName);
            return true;
        }

        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            try
            {   // Don't crash!
                this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }
            catch (Exception ex)
            {
                logger.Debug(ex);
            }
        }
    }
```

When `Chromium.CfxRemotingException` occurs, `ChromiumFXRenderProcess` won't restart anymore and the `HtmlViewControl` is blank.

I still don't understand what the users do, though. Probably this is caused by system shutdown or they kill the Chromium process for fun.

It would be good to catch this exception in Neutronium, if possible, and restart the Chromum process, I think.

**Comment by o2genum** [comment] 2017-11-28 02:42
Ok, sometimes it recovers even after `Chromium.CfxRemotingException`, sometimes it doesn't.

**Comment by David-Desmaisons** [comment] 2017-11-28 13:47
Hi @o2genum , thanks for sharing the scenario and working on reproduction. I will work on improving recuperation on CfxRemotingException.

There already exists a mechanism that try to restart Chromium process in case of unplanned failure. It seems that this mechanism needs to be improved

**Comment by David-Desmaisons** [comment] 2017-11-28 16:19
I was abble to reproduce this unhandled exception with the scenario you mencioned.
I am providing a fix. From what I have seen, your fix in OnPropertyChanged will do the trick before the release of the corrected version.
From my tests, Neutronium is now recovering everytime Chromium process is killed.

**Comment by jmecosta** [comment] 2017-11-28 19:04
@David-Desmaisons i also get the

```
An unhandled exception of type 'Chromium.CfxRemotingException' occurred in WindowsBase.dll
Remote connection lost.


Unhandled Exception: Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt16()
   at Chromium.Remote.RemoteConnection.ReadLoop()
```

does you fix fixes this one or any CfxRemotingException? some users have also experiencing some random crashes so we can also verify this

**Comment by David-Desmaisons** [comment] 2017-11-29 01:20
@jmecosta Well what is your scenario? It will be very usefull if you can share what happens during this crashes. Are they also linked to during system shutdown?

From what we are seeing here, this fix will correct some edge cases when Chromium process is killed most probably during system shutdown.

This is only scenario I am aware of where such an CfxRemotingException exception is not catched by Neutronium. So let me know if this will continue afterthis correction

**Comment by jmecosta** [comment] 2017-11-29 08:07
The one I got was actually during startup. But I will monitor with the fix.
Thanks

**Comment by David-Desmaisons** [comment] 2017-11-29 11:14
@jmecosta Do you application start or system start-up?

**Comment by jmecosta** [comment] 2017-11-29 11:21
At my application startup. Not system. I got that actually launching under
a debug session.  But I had reports of the application crashing while using
it also. For example when when using more than one neutronium controls in
different tabs and swapping between them

**Comment by David-Desmaisons** [comment] 2017-11-29 12:17
@jmecosta Thanks for the information, 
I remenber we discuss your tab solution and the solution was to dispose the Neutronium component when switching tabs.
I am closing this for now. Please re-open an issue with specific scenario if problem persists after this fix.

**Closed by David-Desmaisons** 2017-11-29 12:17 UTC

**Comment by jmecosta** [comment] 2017-11-29 12:34
Yep, and those are in place. Still it sometime crashes. I will keep an eye
on it. Ghay

**Comment by o2genum** [comment] 2017-12-27 01:03
For me, if still won't recover after a while-kill loop. The view gets blank.
```
Neutronium - Error - WebView crashed trying recover
Exception thrown: 'System.IO.IOException' in System.Core.dll
Exception thrown: 'System.IO.IOException' in System.Core.dll
Exception thrown: 'Chromium.CfxRemotingException' in ChromiumFX.dll
Exception thrown: 'System.IO.IOException' in System.Core.dll
Exception thrown: 'Chromium.CfxRemotingException' in ChromiumFX.dll
```
Still no info on what causes it in real use, though.

Is there a way to reload it manually?

**Comment by David-Desmaisons** [comment] 2017-12-27 15:01
@o2genum , if you are seing this trace:
`Neutronium - Error - WebView crashed trying recover`
that means that Neutronium is trying to reload the View.
If the views get blanks and did you display anything that means that the recover process failed.
It will be great to identify better such scenario so that the recovery process can be improved.


> Is there a way to reload it manually?
You can try something like setting the datamodel to null and then back to the original value.

**Comment by jmecosta** [comment] 2018-03-07 11:59
@David-Desmaisons im getting some of the exceptions in the first stack trace by some users.


Application: BuildAllApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.EndOfStreamException
  at System.IO.__Error.EndOfFile()
  at System.IO.BinaryReader.FillBuffer(Int32)
  at System.IO.BinaryReader.ReadUInt16()
  at Chromium.Remote.RemoteConnection.ReadLoop()
  at Chromium.Remote.RemoteConnection.ReadLoopEntry()

Exception Info: Chromium.CfxRemotingException
  at Chromium.Remote.RemoteCall.RequestExecution(Chromium.Remote.RemoteConnection)
  at Chromium.Remote.CfrV8Value.ExecuteFunction(Chromium.Remote.CfrV8Value, Chromium.Remote.CfrV8Value[])
  at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxFactory.CreateFromExcecutionCode(System.Collections.Generic.IEnumerable`1<System.String>)
  at Neutronium.Core.Binding.Builder.JavascriptObjectBulkBuilder.CreateObjects()
  at Neutronium.Core.Binding.Builder.JavascriptObjectBulkBuilder.UpdateJavascriptValue()
  at Neutronium.Core.Binding.BidirectionalMapper+<>c__DisplayClass26_0+<<UpdateJavascriptObjects>b__0>d.MoveNext()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
  at Neutronium.Core.Binding.BidirectionalMapper+<UpdateJavascriptObjects>d__26.MoveNext()
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
  at Neutronium.Core.HtmlBinding+BindingBuilder+<Neutronium-Core-IBindingBuilder-CreateBinding>d__4.MoveNext()

Exception Info: System.AggregateException
  at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResultCore(Boolean)

using latest x64 build, dispose are in code also.  and its intermitent but it does crash here and there

**Comment by simonbuehler** [comment] 2020-07-06 10:24
have the same  issue which prevents the app from running productive, any idea?

```
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.InvalidOperationException
   bei System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)
   bei System.Collections.Generic.Stack`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Pop()
   bei Chromium.Remote.RemoteConnection.ReadLoop()
   bei Chromium.Remote.RemoteConnection.ReadLoopEntry()
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()
```
