### ISSUE TITLE
SPA template doesn't work

### ISSUE THREAD

**Issue by avianate** [NeutroniumCore/Neutronium#87] opened 2018-08-30 21:12 UTC
Can you post a step by step tutorial on how to setup and use Neutronium. The docs leave a lot to be desired and I can't even get the spa template working. There's too many deprecated dependencies

**Comment by David-Desmaisons** [comment] 2018-08-30 21:26
Did you use the Visual studio templates? If not what project did you use?

**Comment by avianate** [comment] 2018-09-04 17:41
I tried using the Neutronium.Vue.Spa1 template

**Comment by shawndrake2** [comment] 2018-11-14 12:41
I actually can't get either Vue template to work. It could definitely be me, I'm new to C# development but I'm super excited about this project. 

The SPA template gives me the following error: 

![neutroniumerrorspatemplate](https://user-images.githubusercontent.com/994776/48483049-559f6480-e7e0-11e8-8614-df8191c54cbb.PNG)

And the Vue Application template gives me this error:

![neutroniumerrorvuetemplate](https://user-images.githubusercontent.com/994776/48483126-95664c00-e7e0-11e8-91c8-3ad027d6112a.PNG)

I didn't try the other template because I was mainly interested in the project with a Vue front end.

**Comment by David-Desmaisons** [comment] 2018-11-14 19:19
I can not reproduce. Make sure that you downloaded and install the template correctly. After project creation you have to restore the nuget to dowload the missing packages and the rebuild.

**Comment by David-Desmaisons** [comment] 2018-11-14 21:58
Here a link to instruction:
https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/SetUp.md

**Comment by David-Desmaisons** [comment] 2018-11-14 21:58
@avianate  Also what is " too many deprecated dependencies"?

**Comment by David-Desmaisons** [comment] 2018-11-14 22:54
You do not have to update nugget dependencies to use the project. See https://github.com/NeutroniumCore/Neutronium.SPA.Demo/issues/2

**Comment by shawndrake2** [comment] 2018-11-17 01:04
@David-Desmaisons thanks for the response. The templates were installed correctly, but I had to install the "Data Sources for SQL Server support" component in order to get past the error with the SPA project. It's building now though, so now I can test it out!

**Comment by shawndrake2** [comment] 2018-11-17 01:06
Spoke too soon. After running the Nuget Restore, I still get the 2nd error I posted above.

**Comment by David-Desmaisons** [comment] 2018-11-17 01:13
There is no dependency beetween  Neutronium and SQL so the error is very likely linked to your environment and not to the template. What is the VS version you are using? Waht are the reproduction steps?

**Comment by David-Desmaisons** [comment] 2018-11-22 23:48
Any feedback on this @shawndrake2 ?

**Comment by shawndrake2** [comment] 2018-11-25 13:02
@David-Desmaisons I was able to get it up and running locally, but to do so I had to run a `nuget restore` first and then upgrade the packages through the nuget management for the solution. I didn't dig in deep enough to see which specific package(s) were causing the issue for me, though.

**Comment by David-Desmaisons** [comment] 2018-11-25 18:48
@shawndrake2 Thanks for the feedback. I am closing this for now. Please feel free to reopen if/when you have a reproducable scenario.

**Closed by David-Desmaisons** 2018-11-25 18:48 UTC
Labels: need reproduction
